name: Release Trained Model

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version the git status
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "tagged=true" >> "$GITHUB_OUTPUT"
          else
            echo "Not a tagged release. Extracting prerelease version"
            VERSION="$(./get_semver.sh)"
            echo "Version: $VERSION"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "tagged=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train_model.py data/a1_RestaurantReviews_HistoricDump.tsv -t 0.0 -o sentiment_model.pkl

      - name: Upload model to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: sentiment_model
          path: sentiment_model.pkl

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          body: |
            Automated release of lib-ml.
            Version: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: ${{ steps.get_version.outputs.prerelease }}
          make_latest: ${{ steps.get_version.outputs.tagged }}
          files: |
            sentiment_model.pkl
